Tidying

diff --git a/src/libreserver-app-flightgear b/src/libreserver-app-flightgear
--- a/src/libreserver-app-flightgear
+++ b/src/libreserver-app-flightgear
@@ -52,7 +52,7 @@ FLIGHTGEAR_DESCRIPTION=$'FlightGear MultiPlayer Server'
 FLIGHTGEAR_MOBILE_APP_URL=""
 
 flightgear_variables=(ONION_ONLY
-					            SYSTEM_TYPE
+                      SYSTEM_TYPE
                       MY_USERNAME)
 
 function upgrade_distro_flightgear {
@@ -65,10 +65,10 @@ function upgrade_distro_flightgear {
 
 function logging_on_flightgear {
     if [ ! -f "${FLIGHTGEAR_DIR}/fgms.conf" ]; then
-		    return
+        return
     fi
     if grep -q "${FLIGHTGEAR_DIR}/fgms.log" "${FLIGHTGEAR_DIR}/fgms.conf"; then
-		    return
+        return
     fi
     sed -i "s|server.logfile.*|server.logfile = ${FLIGHTGEAR_DIR}/fgms.log" "${FLIGHTGEAR_DIR}/fgms.conf"
     systemctl restart fgms
@@ -76,10 +76,10 @@ function logging_on_flightgear {
 
 function logging_off_flightgear {
     if [ ! -f "${FLIGHTGEAR_DIR}/fgms.conf" ]; then
-		    return
+        return
     fi
     if grep -q '/dev/null' "${FLIGHTGEAR_DIR}/fgms.conf"; then
-		    return
+        return
     fi
     sed -i "s|server.logfile.*|server.logfile = /dev/null" "${FLIGHTGEAR_DIR}/fgms.conf"
     systemctl restart fgms
@@ -97,19 +97,19 @@ function reconfigure_flightgear {
 function upgrade_flightgear {
     CURR_FLIGHTGEAR_COMMIT=$(get_completion_param "flightgear commit")
     if [[ "$CURR_FLIGHTGEAR_COMMIT" == "$FLIGHTGEAR_COMMIT" ]]; then
-		    return
+        return
     fi
     function_check set_repo_commit
     set_repo_commit "${INSTALL_DIR}/fgms-src" "flightgear commit" "$FLIGHTGEAR_COMMIT" $FLIGHTGEAR_REPO
     cd "${INSTALL_DIR}/build_fgms" || exit 73
     cmake ../fgms-src
     if [ -f "${INSTALL_DIR}/build_fgms/fgms" ]; then
-		    rm "${INSTALL_DIR}/build_fgms/fgms"
+        rm "${INSTALL_DIR}/build_fgms/fgms"
     fi
     make
     if [ ! -f "${INSTALL_DIR}/build_fgms/fgms" ]; then
-		    echo "Failed to upgrade fgms to commit $FLIGHTGEAR_COMMIT"
-		    return
+        echo "Failed to upgrade fgms to commit $FLIGHTGEAR_COMMIT"
+        return
     fi
     make install
     systemctl restart fgms
@@ -175,7 +175,7 @@ function remove_flightgear {
         rm -rf "${FLIGHTGEAR_DIR}"
     fi
     if [ -f ${FLIGHTGEAR_FILENAME} ]; then
-		    rm ${FLIGHTGEAR_FILENAME}
+        rm ${FLIGHTGEAR_FILENAME}
     fi
 
     remove_app flightgear
@@ -196,14 +196,14 @@ function install_flightgear {
     fi
 
     if ! grep -q "fgms:" /etc/group; then
-		    groupadd fgms
+        groupadd fgms
     fi
     useradd -c "Flightgear Multiplayer" -d "${FLIGHTGEAR_DIR}" -m -r -g fgms fgms
 
     increment_app_install_progress
 
     if [ ! -d /var/games ]; then
-		    mkdir /var/games
+        mkdir /var/games
     fi
 
     if [ -d /var/www/flightgear ]; then
@@ -233,20 +233,20 @@ function install_flightgear {
     increment_app_install_progress
     make
     if [ ! -f "${INSTALL_DIR}/build_fgms/fgms" ]; then
-		    echo "Failed to build fgms"
-		    exit 75
+        echo "Failed to build fgms"
+        exit 75
     fi
     increment_app_install_progress
     make install
     if [ ! -f ${FLIGHTGEAR_FILENAME} ]; then
-		    echo "Failed to install ${FLIGHTGEAR_FILENAME}"
-		    exit 76
+        echo "Failed to install ${FLIGHTGEAR_FILENAME}"
+        exit 76
     fi
 
     increment_app_install_progress
 
     if [ ! -d ${FLIGHTGEAR_DIR} ]; then
-		    mkdir ${FLIGHTGEAR_DIR}
+        mkdir ${FLIGHTGEAR_DIR}
     fi
 
     increment_app_install_progress
diff --git a/src/libreserver-email-avatar b/src/libreserver-email-avatar
--- a/src/libreserver-email-avatar
+++ b/src/libreserver-email-avatar
@@ -35,40 +35,40 @@ fi
 if [ ! -f /usr/bin/ffmpeg ]; then
     sudo apt-get install -y ffmpeg
     if [ ! -f /usr/bin/ffmpeg ]; then
-	echo 'Failed to install ffmpeg'
-	exit 2
+        echo 'Failed to install ffmpeg'
+        exit 2
     fi
 fi
 
 if [ ! -f /usr/bin/compface ]; then
     sudo apt-get install -y compface
     if [ ! -f /usr/bin/compface ]; then
-	echo 'Failed to install compface'
-	exit 3
+        echo 'Failed to install compface'
+        exit 3
     fi
 fi
 
 if [[ "$SOURCE_IMAGE" == 'http'* ]]; then
     temp_image=~/.avatar_temp
     if [[ "$SOURCE_IMAGE" == *'.jpg' || "$SOURCE_IMAGE" == *'.jpeg' ]]; then
-	temp_image=~/.avatar_temp.jpg
+        temp_image=~/.avatar_temp.jpg
     fi
     if [[ "$SOURCE_IMAGE" == *'.gif' ]]; then
-	temp_image=~/.avatar_temp.gif
+        temp_image=~/.avatar_temp.gif
     fi
     if [[ "$SOURCE_IMAGE" == *'.png' ]]; then
-	temp_image=~/.avatar_temp.png
+        temp_image=~/.avatar_temp.png
     fi
     if [[ "$SOURCE_IMAGE" == *'.webp' ]]; then
-	temp_image=~/.avatar_temp.webp
+        temp_image=~/.avatar_temp.webp
     fi
     if [ -f $temp_image ]; then
-	rm $temp_image
+        rm $temp_image
     fi
     wget "$SOURCE_IMAGE" -O $temp_image
     if [ ! -f $temp_image ]; then
-	echo "Failed to get $SOURCE_IMAGE"
-	exit 6
+        echo "Failed to get $SOURCE_IMAGE"
+        exit 6
     fi
     SOURCE_IMAGE=$temp_image
 fi
@@ -99,18 +99,18 @@ fi
 
 if [ -f ~/.muttrc ]; then    
     if grep -q 'X-Face:' ~/.muttrc; then
-	sed -i '/X-Face:/d' ~/.muttrc
+        sed -i '/X-Face:/d' ~/.muttrc
     fi
     echo -n "my_hdr X-Face: $(compface $AVATAR_IMAGE | muttquote-x-face )" >> ~/.muttrc
     echo 'Avatar added to mutt header'
 
     if ! grep -q 'unignore x-face' ~/.muttrc; then
-	echo 'unignore x-face' >> ~/.muttrc
-	echo 'Show x-face header in mutt'
+        echo 'unignore x-face' >> ~/.muttrc
+        echo 'Show x-face header in mutt'
     fi
     if ! grep -q 'view-x-face' ~/.muttrc; then
-	echo "macro pager \ef \"|/usr/local/bin/view-x-face<enter>\" \"display the X-Face included in the mail\"" >> ~/.muttrc
-	echo 'Added avatar display to mutt'
+        echo "macro pager \ef \"|/usr/local/bin/view-x-face<enter>\" \"display the X-Face included in the mail\"" >> ~/.muttrc
+        echo 'Added avatar display to mutt'
     fi
 fi
 
