Installing staticmap within virtualenv

diff --git a/src/libreserver-utils-map b/src/libreserver-utils-map
--- a/src/libreserver-utils-map
+++ b/src/libreserver-utils-map
@@ -68,19 +68,25 @@ function install_static_map {
         INSTALL_PACKAGES libjpeg-dev python3-pip python3-socks python3-stem python3-setuptools python3-wheel python3-dev python3-requests python3-pil
     fi
 
+    if [ -d /etc/staticmap ]; then
+        rm -rf /etc/staticmap
+    fi
+    mkdir /etc/staticmap
+
     { echo '#!/bin/bash';
-      echo "git clone \"$MAP_REPO\" /etc/staticmap";
       echo 'cd /etc/staticmap || exit 1';
-      echo "git checkout $MAP_COMMIT -b $MAP_COMMIT";
       echo 'virtualenv -p python3 .venv';
-      echo 'if ! pip3 install -r requirements.txt; then';
-      echo '    deactivate';
-      echo '    echo "WARN: Failed to install dependencies for staticmap"';
-      echo '    rm -rf /etc/staticmap';
-      echo '    exit 2';
-      echo 'else';
-      echo '    deactivate';
-      echo 'fi'; } > "$rootdir/root/install_static_map.sh"
+      echo "git clone \"$MAP_REPO\" staticmap";
+      echo 'if [ -d staticmap ]; then';
+      echo "    git checkout $MAP_COMMIT -b $MAP_COMMIT";
+      echo '    if ! pip3 install -r requirements.txt; then';
+      echo '        echo "WARN: Failed to install dependencies for staticmap"';
+      echo '        rm -rf /etc/staticmap';
+      echo '        deactivate';
+      echo '        exit 3';
+      echo '    fi';
+      echo 'fi';
+      echo 'deactivate'; } > "$rootdir/root/install_static_map.sh"
     chmod +x "$rootdir/root/install_static_map.sh"
 
     if [ "$rootdir" ]; then
@@ -227,6 +233,7 @@ function create_map {
     { echo '#!/bin/bash';
       echo 'cd /etc/staticmap || return 1';
       echo 'virtualenv -p python3 .venv';
+      echo 'cd staticmap'
       echo 'python3 generate_map.py';
       echo 'deactivate'; } > /usr/bin/generate_map
     chmod +x /usr/bin/generate_map
