Copy prosody modules directory if needed

diff --git a/src/libreserver-app-xmpp b/src/libreserver-app-xmpp
--- a/src/libreserver-app-xmpp
+++ b/src/libreserver-app-xmpp
@@ -52,6 +52,8 @@ XMPP_PASSWORD=
 XMPP_CIPHERS='EDH+CAMELLIA:EDH+aRSA:EECDH+aRSA+AESGCM:EECDH+aRSA+SHA256:EECDH:+CAMELLIA128:+AES128:+SSLv3:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!DSS:!RC4:!SEED:!IDEA:!ECDSA:kEDH:CAMELLIA128-SHA:AES128-SHA'
 XMPP_ECC_CURVE='secp384r1'
 
+# separate prosody modules are used so that the latest improvements can be
+# utilised even if the Debian packaged ones are out of date.
 # From https://hg.prosody.im/prosody-modules
 prosody_modules_filename='prosody-modules-20250725.tar.gz'
 prosody_modules_hash='0084a3644bb57efb5cdc9465fa52fc5b0901c10e25a5983f735c870baa0ed5dd'
@@ -754,48 +756,68 @@ function reconfigure_xmpp {
 function update_prosody_modules {
     if [ ! "$1" ]; then
         if [ ! -d ${XMPP_DIRECTORY}/prosody-modules ]; then
-            return
+            if [ -d "${INSTALL_DIR}/prosody-modules" ]; then
+                # use the downloaded prosody modules
+                mkdir -p ${XMPP_DIRECTORY}/prosody-modules
+                cp -r "${INSTALL_DIR}/prosody-modules/"* ${XMPP_DIRECTORY}/prosody-modules/
+                cp -r "${INSTALL_DIR}/prosody-modules/"* /usr/lib/prosody/modules/
+                if [ -f ${XMPP_DIRECTORY}/prosody-modules/mod_i2p ]; then
+                    rm ${XMPP_DIRECTORY}/prosody-modules/mod_i2p
+                fi
+                if [ -f /usr/lib/prosody/modules/mod_i2p ]; then
+                    rm /usr/lib/prosody/modules/mod_i2p
+                fi
+                if [ -d "/root/${PROJECT_NAME}/image_build/prosody_mod_i2p" ]; then
+                    cp -r "/root/${PROJECT_NAME}/image_build/prosody_mod_i2p" ${XMPP_DIRECTORY}/prosody-modules/mod_i2p
+                    cp -r "/root/${PROJECT_NAME}/image_build/prosody_mod_i2p" /usr/lib/prosody/modules/mod_i2p
+                fi
+
+                chown -R prosody:prosody ${XMPP_DIRECTORY}/prosody-modules
+                chown -R prosody:prosody /usr/lib/prosody/modules
+            else
+                return
+            fi
         fi
     fi
     if [ ! -d /usr/lib/prosody ]; then
         return
     fi
 
-    if [ ! -f "$INSTALL_DIR/$prosody_modules_filename" ]; then
+    if [ ! -f "${INSTALL_DIR}/$prosody_modules_filename" ]; then
         xmpp_restart=1
 
         # Obtain the modules
         if [ -f "/root/${PROJECT_NAME}/image_build/$prosody_modules_filename" ]; then
-            echo "Copying $prosody_modules_filename to $INSTALL_DIR"
-            cp "/root/${PROJECT_NAME}/image_build/$prosody_modules_filename" "$INSTALL_DIR"
+            echo "Copying $prosody_modules_filename to ${INSTALL_DIR}"
+            cp "/root/${PROJECT_NAME}/image_build/$prosody_modules_filename" "${INSTALL_DIR}"
         else
             if [ -f "/home/$MY_USERNAME/${PROJECT_NAME}/image_build/$prosody_modules_filename" ]; then
-                echo "Copying $prosody_modules_filename to $INSTALL_DIR"
-                cp "/home/$MY_USERNAME/${PROJECT_NAME}/image_build/$prosody_modules_filename" "$INSTALL_DIR"
+                echo "Copying $prosody_modules_filename to ${INSTALL_DIR}"
+                cp "/home/$MY_USERNAME/${PROJECT_NAME}/image_build/$prosody_modules_filename" "${INSTALL_DIR}"
             fi
         fi
 
-        if [ -f "$INSTALL_DIR/$prosody_modules_filename" ]; then
-            cd "$INSTALL_DIR" || exit 24
+        if [ -f "${INSTALL_DIR}/$prosody_modules_filename" ]; then
+            cd "${INSTALL_DIR}" || exit 24
 
             # Check the hash
-            curr_hash=$(sha256sum "$INSTALL_DIR/$prosody_modules_filename" | awk -F ' ' '{print $1}')
+            curr_hash=$(sha256sum "${INSTALL_DIR}/$prosody_modules_filename" | awk -F ' ' '{print $1}')
             if [[ "$curr_hash" != "$prosody_modules_hash" ]]; then
                 echo $'Prosody modules hash does not match'
                 exit 83
             else
                 # Extract the modules
-                if [ -d "$INSTALL_DIR/prosody-modules" ]; then
-                    rm -rf "$INSTALL_DIR/prosody-modules"
+                if [ -d "${INSTALL_DIR}/prosody-modules" ]; then
+                    rm -rf "${INSTALL_DIR}/prosody-modules"
                 fi
                 tar -xzvf $prosody_modules_filename
-                if [ -d "$INSTALL_DIR/prosody-modules" ]; then
+                if [ -d "${INSTALL_DIR}/prosody-modules" ]; then
                     systemctl stop prosody
                     if [ ! -d ${XMPP_DIRECTORY}/prosody-modules ]; then
                         mkdir -p ${XMPP_DIRECTORY}/prosody-modules
                     fi
-                    cp -r "$INSTALL_DIR/prosody-modules/"* ${XMPP_DIRECTORY}/prosody-modules/
-                    cp -r "$INSTALL_DIR/prosody-modules/"* /usr/lib/prosody/modules/
+                    cp -r "${INSTALL_DIR}/prosody-modules/"* ${XMPP_DIRECTORY}/prosody-modules/
+                    cp -r "${INSTALL_DIR}/prosody-modules/"* /usr/lib/prosody/modules/
                     if [ -f ${XMPP_DIRECTORY}/prosody-modules/mod_i2p ]; then
                         rm ${XMPP_DIRECTORY}/prosody-modules/mod_i2p
                     fi
@@ -816,7 +838,7 @@ function update_prosody_modules {
                 fi
             fi
         else
-            echo "Can't find prosody modules $INSTALL_DIR/$prosody_modules_filename"
+            echo "Can't find prosody modules ${INSTALL_DIR}/$prosody_modules_filename"
         fi
     fi
 
@@ -937,6 +959,12 @@ function upgrade_xmpp {
         systemctl restart prosody
     fi
 
+    # replace block_strangers module
+    if grep -q 'block_strangers' /etc/prosody/prosody.cfg.lua; then
+        sed -i 's|block_strangers|poke_strangers|g' /etc/prosody/prosody.cfg.lua
+        systemctl restart prosody
+    fi
+
     # deprecated module
     if grep -q 'smacks_offline' /etc/prosody/prosody.cfg.lua; then
         sed -i '/smacks_offline/d' /etc/prosody/prosody.cfg.lua
@@ -1027,6 +1055,9 @@ function upgrade_xmpp {
     # old reactions, now integrated into muc
     prosody_remove_module "muc_occupantid"
 
+    prosody_remove_module "block_strangers"
+    prosody_add_module "poke_strangers"
+
     # security labels
     prosody_add_module "seclabels"
     prosody_default_security_labels /etc/prosody/prosody.cfg.lua
@@ -1083,7 +1114,7 @@ function upgrade_xmpp {
     chown -R root:root /lib/prosody
 
     if [ $xmpp_restart ]; then
-        cp -r "$INSTALL_DIR/prosody-modules/"* ${XMPP_DIRECTORY}/prosody-modules/
+        cp -r "${INSTALL_DIR}/prosody-modules/"* ${XMPP_DIRECTORY}/prosody-modules/
         chown -R prosody:prosody ${XMPP_DIRECTORY}/prosody-modules
 
         echo $'Restarting prosody'
@@ -1191,11 +1222,11 @@ function remove_xmpp {
 
     $REMOVE_PACKAGES_PURGE prosody go-sendxmpp
     rm /etc/cron.daily/prosody
-    if [ -f "$INSTALL_DIR/$prosody_modules_filename" ]; then
-        rm "$INSTALL_DIR/$prosody_modules_filename"
+    if [ -f "${INSTALL_DIR}/$prosody_modules_filename" ]; then
+        rm "${INSTALL_DIR}/$prosody_modules_filename"
     fi
-    if [ -d "$INSTALL_DIR/prosody-modules" ]; then
-        rm -rf "$INSTALL_DIR/prosody-modules"
+    if [ -d "${INSTALL_DIR}/prosody-modules" ]; then
+        rm -rf "${INSTALL_DIR}/prosody-modules"
     fi
     if [ -d /etc/prosody ]; then
         rm -rf /etc/prosody
@@ -1681,7 +1712,7 @@ function remove_upstream_xmpp_package {
     fi
     echo $'Removing upstream prosody package'
     INSTALL_DIR=$HOME/build
-    REMOVE_XMPP_DIR=$INSTALL_DIR/remove_xmpp_package
+    REMOVE_XMPP_DIR=${INSTALL_DIR}/remove_xmpp_package
     if [ ! -d "$REMOVE_XMPP_DIR" ]; then
         mkdir -p "$REMOVE_XMPP_DIR"
     fi
@@ -1709,16 +1740,16 @@ function remove_upstream_xmpp_package {
 function install_xmpp {
     increment_app_install_progress
 
-    if [ ! -d "$INSTALL_DIR" ]; then
-        mkdir -p "$INSTALL_DIR"
+    if [ ! -d "${INSTALL_DIR}" ]; then
+        mkdir -p "${INSTALL_DIR}"
     fi
 
     # remove any existing install attempt
-    if [ -f "$INSTALL_DIR/$prosody_modules_filename" ]; then
-        rm "$INSTALL_DIR/$prosody_modules_filename"
+    if [ -f "${INSTALL_DIR}/$prosody_modules_filename" ]; then
+        rm "${INSTALL_DIR}/$prosody_modules_filename"
     fi
-    if [ -d "$INSTALL_DIR/prosody-modules" ]; then
-        rm -rf "$INSTALL_DIR/prosody-modules"
+    if [ -d "${INSTALL_DIR}/prosody-modules" ]; then
+        rm -rf "${INSTALL_DIR}/prosody-modules"
     fi
 
     increment_app_install_progress
