Copy file later

diff --git a/src/libreserver-app-cryptpad b/src/libreserver-app-cryptpad
--- a/src/libreserver-app-cryptpad
+++ b/src/libreserver-app-cryptpad
@@ -156,6 +156,14 @@ function cryptpad_generate_api_config {
 }
 
 function upgrade_cryptpad {
+    if [ ! -f ${CRYPTPAD_DIR}/customize/application_config.js ]; then
+        if [ ! -d ${CRYPTPAD_DIR}/customize ]; then
+            mkdir ${CRYPTPAD_DIR}/customize
+        fi
+        cp ${CRYPTPAD_DIR}/customize.dist/application_config.js ${CRYPTPAD_DIR}/customize/application_config.js
+        chmod 755 ${CRYPTPAD_DIR}/customize/application_config.js
+    fi
+
     cryptpad_turn_off_signups
     cryptpad_evict_inactive_data
 
@@ -568,18 +576,6 @@ function install_cryptpad {
 
     increment_app_install_progress
 
-    if [ ! -d ${CRYPTPAD_DIR}/customize ]; then
-        mkdir ${CRYPTPAD_DIR}/customize
-    fi
-    cp ${CRYPTPAD_DIR}/customize.dist/application_config.js ${CRYPTPAD_DIR}/customize/application_config.js
-
-    if [ ! -f ${CRYPTPAD_DIR}/customize/application_config.js ]; then
-        echo $'Failed to copy application_config.js'
-        exit 72
-    fi
-
-    increment_app_install_progress
-
     chown -R cryptpad:cryptpad ${CRYPTPAD_DIR}
 
     increment_app_install_progress
@@ -642,6 +638,21 @@ function install_cryptpad {
     chmod -R 755 /var/www/cryptpad
 
     systemctl restart nginx
+
+    increment_app_install_progress
+
+    if [ ! -d ${CRYPTPAD_DIR}/customize ]; then
+        mkdir ${CRYPTPAD_DIR}/customize
+    fi
+    cp ${CRYPTPAD_DIR}/customize.dist/application_config.js ${CRYPTPAD_DIR}/customize/application_config.js
+
+    if [ ! -f ${CRYPTPAD_DIR}/customize/application_config.js ]; then
+        echo $'Failed to copy application_config.js'
+        exit 72
+    fi
+    chmod 755 ${CRYPTPAD_DIR}/customize/application_config.js
+
+    increment_app_install_progress
 
     cryptpad_initial_login=$(systemctl status cryptpad | grep "http://" | head -n 1 | awk -F ': ' '{print $2}')
 
