Cryptpad nginx config

diff --git a/src/libreserver-app-cryptpad b/src/libreserver-app-cryptpad
--- a/src/libreserver-app-cryptpad
+++ b/src/libreserver-app-cryptpad
@@ -460,6 +460,13 @@ function install_cryptpad_main {
       echo "  set \$api_domain \"${CRYPTPAD_ONION_HOSTNAME}\";";
       echo "  set \$files_domain \"${CRYPTPAD_ONION_HOSTNAME}\";";
       echo '';
+      echo "  set \$coop '';";
+      echo "  if (\$uri ~ ^\/(sheet|presentation|doc)\/.*\$) { set \$coop 'same-origin'; }";
+      echo '';
+      echo '  add_header Cross-Origin-Resource-Policy cross-origin;';
+      echo "  add_header Cross-Origin-Opener-Policy \$coop;";
+      echo '  add_header Cross-Origin-Embedder-Policy require-corp;';
+      echo '';
       echo "  server_name ${CRYPTPAD_ONION_HOSTNAME};";
       echo '';
       echo "  add_header X-XSS-Protection \"1; mode=block\";";
@@ -538,8 +545,8 @@ function install_cryptpad_main {
       echo '      add_header Cache-Control max-age=31536000;';
       echo "      add_header 'Access-Control-Allow-Origin' '*';";
       echo "      add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';";
-      echo "      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';";
-      echo "      add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';";
+      echo "      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Content-Length';";
+      echo "      add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Content-Length';";
       echo "      try_files \$uri =404;";
       echo '  }';
       echo '';
@@ -555,7 +562,7 @@ function install_cryptpad_main {
       echo "    try_files \$uri =404;";
       echo '  }';
       echo '';
-      echo '  location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media|profile|contacts|todo|filepicker|debug|kanban|sheet|support|admin|notifications|teams)$ {';
+      echo '  location ~ ^/(register|login|settings|user|pad|drive|poll|slide|code|whiteboard|file|media|profile|contacts|todo|filepicker|debug|kanban|sheet|support|admin|notifications|teams|calendar|presentation|doc)$ {';
       echo "      rewrite ^(.*)\$ \$1/ redirect;";
       echo '  }';
       echo '';
@@ -586,11 +593,11 @@ function install_cryptpad {
     /usr/bin/npm install -g bower
     # git config --global url."https://".insteadOf git://
     if [ ! -f /usr/bin/bower ]; then
-	echo 'Unable to install bower'
-	exit 46
+        echo 'Unable to install bower'
+        exit 46
     fi
     if [ ! -d ${CRYPTPAD_DIR}/tmp ]; then
-	mkdir ${CRYPTPAD_DIR}/tmp
+        mkdir ${CRYPTPAD_DIR}/tmp
     fi
     TMPDIR=${CRYPTPAD_DIR}/tmp /usr/bin/bower install
     TMPDIR=/tmp
